export const CONTRACT_ADDRESS = '0xd0AaB8B4A6e7Cc32B199d32E8856ce07a3797324'
export const CONTRACT_ABI = [
  'constructor(address[],uint256[]) payable',
  'event Approval(address indexed,address indexed,uint256 indexed)',
  'event ApprovalForAll(address indexed,address indexed,bool)',
  'event ERC20PaymentReleased(address indexed,address,uint256)',
  'event OwnershipTransferred(address indexed,address indexed)',
  'event PayeeAdded(address,uint256)',
  'event PaymentReceived(address,uint256)',
  'event PaymentReleased(address,uint256)',
  'event Transfer(address indexed,address indexed,uint256 indexed)',
  'function approve(address,uint256)',
  'function balanceOf(address) view returns (uint256)',
  'function freeMint(address)',
  'function getApproved(uint256) view returns (address)',
  'function isApprovedForAll(address,address) view returns (bool)',
  'function listTokenOf(address) view returns (uint256[])',
  'function name() view returns (string)',
  'function owner() view returns (address)',
  'function ownerOf(uint256) view returns (address)',
  'function payee(uint256) view returns (address)',
  'function publicMint(address) payable',
  'function release(address)',
  'function release(address,address)',
  'function released(address,address) view returns (uint256)',
  'function released(address) view returns (uint256)',
  'function renounceOwnership()',
  'function safeTransferFrom(address,address,uint256)',
  'function safeTransferFrom(address,address,uint256,bytes)',
  'function setApprovalForAll(address,bool)',
  'function shares(address) view returns (uint256)',
  'function supportsInterface(bytes4) view returns (bool)',
  'function symbol() view returns (string)',
  'function test_maxSupply()',
  'function test_resetSupply()',
  'function tokenURI(uint256) view returns (string)',
  'function totalReleased(address) view returns (uint256)',
  'function totalReleased() view returns (uint256)',
  'function totalShares() view returns (uint256)',
  'function totalSupply() view returns (uint256)',
  'function transferFrom(address,address,uint256)',
  'function transferOwnership(address)',
]
